name: Run Option Analysis

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 12 * * *"  # Запуск каждый день в 12:00 UTC

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas

      - name: Run script
        run: python process_options.py
        
      - name: Install dependencies
        run: pip install gspread google-auth pandas
        
      - name: Set up Google Drive credentials
        run: echo '${{ secrets.GDRIVE_CREDENTIALS }}' > service_account.json
