name: Run Option Analysis

on:
  schedule:
    - cron: "0 12 * * *"  # Запуск каждый день в 12:00 UTC
  workflow_dispatch:  # Оставляем только ручной запуск

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install pandas gspread google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client pyTelegramBotAPI

      - name: Debug Secrets
        run: echo "Checking if GDRIVE_CREDENTIALS exists"; if [ -z "${{ secrets.GDRIVE_CREDENTIALS }}" ]; then echo "GDRIVE_CREDENTIALS is missing!"; exit 1; fi

      - name: Set up Google Drive credentials
        run: echo '${{ secrets.GDRIVE_CREDENTIALS }}' > service_account.json

      - name: Run script
        run: python process_options.py

